### ISSUE TITLE
Not working with web

### ISSUE THREAD

**Issue by Tonku** [xquezme/WebRTC#1]
Hi Bro,
I have tested it with one iOS and other google chrome in Mac , it did not work.
But iOS to iOS works just fine , any help appreciated

**Comment by xquezme** [comment]
Hey. If u using https://apprtc.appspot.com, try https://appr.tc instead.
Seems like the first one outdated a little.

**Comment by Tonku** [comment]
What is the difference between the two urls..?

**Comment by xquezme** [comment]
The second one is officially web app developed by Google and Mozilla (https://webrtc.org/reference-apps/).

Also, you can change config params in `ARDAppEngineClient.m` manually.

``` objc
static NSString * const kARDRoomServerHostUrl =
    @"https://appr.tc";
static NSString * const kARDRoomServerJoinFormat =
    @"https://appr.tc/join/%@";
static NSString * const kARDRoomServerJoinFormatLoopback =
    @"https://appr.tc/join/%@?debug=loopback";
static NSString * const kARDRoomServerMessageFormat =
    @"https://appr.tc/message/%@/%@";
static NSString * const kARDRoomServerLeaveFormat =
    @"https://appr.tc/leave/%@/%@";
```

**Comment by Tonku** [comment]
Thanks !
