### ISSUE TITLE
dyld: Library not loaded: /System/Library/Frameworks/MetalKit.framework/MetalKit

### ISSUE THREAD

**Issue by CoderXLL** [xquezme/WebRTC#6]
I have added framework to the target,but only run the framework on 8.1 simulators ,it doesn't work, the error is this:
dyld: Library not loaded: /System/Library/Frameworks/MetalKit.framework/MetalKit
Referenced from: /private/var/mobile/Containers/Bundle/Application/8454DA05-F872-497A-A44A-F6261169E57B/EUCIMManager.app/Frameworks/WebRTC.framework/WebRTC
Reason: image not found

**Comment by kai60** [comment]
add copy files  of this framework   will do!
